"""fix unique condition

Revision ID: a82e0b91483b
Revises: fb0da8921c0e
Create Date: 2025-11-21 15:08:49.269913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82e0b91483b'
down_revision: Union[str, Sequence[str], None] = 'fb0da8921c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('job_posts_title_key'), 'job_posts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('job_posts_title_key'), 'job_posts', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
