"""fix column name

Revision ID: fb0da8921c0e
Revises: d9a3e8f5407b
Create Date: 2025-11-21 15:03:51.999267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0da8921c0e'
down_revision: Union[str, Sequence[str], None] = 'd9a3e8f5407b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('job_board_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('job_posts_jobBoard_id_fkey'), 'job_posts', type_='foreignkey')
    op.create_foreign_key(None, 'job_posts', 'job_boards', ['job_board_id'], ['id'])
    op.drop_column('job_posts', 'jobBoard_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('jobBoard_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_posts', type_='foreignkey')
    op.create_foreign_key(op.f('job_posts_jobBoard_id_fkey'), 'job_posts', 'job_boards', ['jobBoard_id'], ['id'])
    op.drop_column('job_posts', 'job_board_id')
    # ### end Alembic commands ###
